[package]
name = "leetcode"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cargo = "0.73.1"
dotenvy_macro = "0.15.7"
html2md = "0.2.14"
leetcoderustapi = "1.0.6"
tokio = "1.32.0"
